const NAME = Object.freeze(new Enum(
    "ALICE",
    "ANAJU",
    "ANDRE",
    "ARTHUR",
    "BERNAD",
    "BRUNA",
    "CAIO",
    "DANILO",
    "EUDA",
    "FGOIS",
    "FBARRETO",
    "FSANCHEZ",
    "HENRIQUE",
    "JP",
    "JOATAN",
    "ISABELLA",
    "MAYANNE",
    "MARCELO",
    "MATHEUS",
    "IKARO",
    "JVPORTO",
    "JVROCHA",
    "JONATAS",
    "ISRAEL",
    "MARIALUISA",
    "MARIANNA",
    "INGRID",
    "JOAS",
    "PAULA",
    "RAFAEL",
    "THALIA",
    "VICTORIA",
    "WILLISTON",
    "JUAN",
    "LAIS",
    "LILIAN",
    "LUIS",
    "MELINA",
    "MICCHAEL",
    "MILENA",
    "NILTON",
    "SAMUEL",
    "ARAUJO",
    "NATHALIA",
    "GABRIEL",
    "DENISE",
    "ELISIANY",
    "MARLUS",
    "BRUNELY",
    "SHEILA",
    "TOTAL"
));

function NameManager(){
  this.names = [
    ["ALICE", "ALICE"],
    ["ANA JULIA", "ANA JULIA"],
    ["ANDRE", "ANDREW"],
    ["ARTHUR", "ARTHUR"],
    ["BERNAD", "HIBERNA"],
    ["BRUNA", "BRUNA"],
    ["CAIO", "FALL"],
    ["DANILO", "DAN"],
    ["EUDA","EUDA"],
    ["FELIPE GOIS", "PHILLIP GOES"],
    ["BARRETO","BARRETO"],
    ["SANCHEZ","SANCHEZ"],
    ["HENRIQUE","HENRY"],
    ["JOAO PAULO","JOHN PAUL"],
    ["JOATAN","JOATAN"],
    ["ISABELLA","ISABELL"],
    ["MAYANNE","MAY ANNE"],
    ["MARCELO","MARCELO"],
    ["MATHEUS","MATTHEW"],
    ["IKARO","ICARUS"],
    ["JV PORTO","JV HARBOR"],
    ["JV ROCHA","JV ROCK"],
    ["JONATAS","JONATAS"],
    ["ISRAEL","ISRAEL"],
    ["MARIA LUISA","MARY LOUISE"],
    ["MARIANNA","MARY ANNE"],
    ["INGRID","HINGRID"],
    ["JOAS","JOSHUA"],
    ["PAULA","PAULINE"],
    ["DANTAS","DONATELO"],
    ["THALIA","ITALIA"],
    ["VICTORIA","VICTORY"],
    ["WILLISTON","NOT SILLIW"],
    ["JUAN","JUAN"],
    ["LAIS","LAYS"],
    ["LILIAN","LILIAN"],
    ["LUIS","LOUIS"],
    ["MELINA","HONEY-INA"],
    ["MICCHAEL","JACKSON"],
    ["MILENA","THOUSAND-ENA"],
    ["NILTON","NEWTON"],
    ["SAMUEL","SAM"],
    ["ARAUJO","MICKELANGELO"],
    ["NATHALIA","NATALINA"],
    ["GABRIEL","GABRIEL"],
    ["DENISE","DENISE"],
    ["ELISIANY","ELISIANY"],
    ["MARLUS","MARCOS"],
    ["BRUNELY","BRUNELY"],
    ["SHEILA", "SHEILA"],
  ];
}

var nameMan = new NameManager();
