const NAME = Object.freeze(new Enum(
    "ALICE",
    "ANAJU",
    "ANDRE",
    "ARTHUR",
    "BERNAD",
    "BRUNA",
    "CAIO",
    "DANILO",
    "EUDA",
    "FGOIS",
    "FBARRETO",
    "FSANCHEZ",
    "HENRIQUE",
    "JP",
    "JOATAN",
    "ISABELLA",
    "MAYANNE",
    "MARCELO",
    "MATHEUS",
    "IKARO",
    "JVPORTO",
    "JVROCHA",
    "JONATAS",
    "ISRAEL",
    "MARIALUISA",
    "MARIANNA",
    "INGRID",
    "JOAS",
    "PAULA",
    "RAFAEL",
    "THALIA",
    "VICTORIA",
    "WILLISTON",
    "JUAN",
    "LAIS",
    "LILIAN",
    "LUIS",
    "MELINA",
    "MICCHAEL",
    "MILENA",
    "NILTON",
    "SAMUEL",
    "ARAUJO",
    "NATHALIA",
    "GABRIEL",
    "DENISE",
    "ELISIANY",
    "MARLUS",
    "BRUNELY",
    "SHEILA",
    "TOTAL"
));

function NameManager(){
  this.names = [
    ["ALICE", "ALICE"],
    ["ANA JULIA", "ANA JULIA"],
    ["ANDRE", "ANDREW"],
    ["ARTHUR", "ARTHUR"],
    ["BERNAD", "HIBERNA"],
    ["BRUNA", "BRUNA"],
    ["CAIO", "FALL"],
    ["DANILO", "DAN"],
    ["EUDA","EUDA"],
    ["FELIPE GOIS", "FELIPE GOES"],
    ["FELIPE BARRETO","FELIPE BARRETO"],
    ["FELIPE SANCHEZ","FELIPE SANCHEZ"],
    ["HENRIQUE","HENRY"],
    ["JOAO PAULO","JOHN PAUL"],
    ["JOATAN","JOATAN"],
    ["ISABELLA","ISABELL"],
    ["MAYANNE","MAY ANNE"],
    ["MARCELO","MARCELO"],
    ["MATHEUS","MATTHEW"],
    ["IKARO","ICARUS"],
    ["JV PORTO","JV HARBOR"],
    ["JV ROCHA","JV ROCK"],
    ["JONATAS","JONATAS"],
    ["ISRAEL","ISRAEL"],
    ["MARIA LUISA","MARY LOUISE"],
    ["MARIANNA","MARY ANNE"],
    ["INGRID","HINGRID"],
    ["JOAS","JOSHUA"],
    ["PAULA","PAULINE"],
    ["RAFAEL","DONATELO"],
    ["THALIA","ITALIA"],
    ["VICTORIA","VICTORY"],
    ["WILLISTON","NOT SILLIW"],
    ["JUAN","JUAN"],
    ["LAIS","LAYS"],
    ["LILIAN","LILIAN"],
    ["LUIS","LOUIS"],
    ["MELINA","HONEY-INA"],
    ["MICCHAEL","JACKSON"],
    ["MILENA","THOUSAND-ENA"],
    ["NILTON","NEWTON"],
    ["SAMUEL","SAM"],
    ["RAFAEL ARAUJO","MICKELANGELO"],
    ["NATHALIA","NATALINA"],
    ["GABRIEL","GABRIEL"],
    ["DENISE","DENISE"],
    ["ELISIANY","ELISIANY"],
    ["MARLUS","MARCOS"],
    ["BRUNELY","BRUNELY"],
    ["SHEILA", "SHEILA"],
  ];

  this.altNames = [
    "ALICE",
    "ANA JULIA",
    "ANDREW",
    "ARTHUR",
    "HIBERNA",
    "BRUNA",
    "FALL",
    "DAN",
    "EUDA",
    "FELIPE GOIS",
    "FELIPE BARRETO",
    "FELIPE SANCHEZ",
    "HENRY",
    "JOHN PAUL",
    "JOATAN",
    "ISABELL",
    "MAY ANNE",
    "MARCELO",
    "MATTHEW",
    "ICARUS",
    "JV PORTO",
    "JV ROCK",
    "JONATAS",
    "ISRAEL",
    "MARY LOUISE",
    "MARIANNA",
    "INGRID",
    "JOSHUA",
    "PAULINE",
    "RAPHAEL",
    "ITALIA",
    "VICTORY",
    "WILLISTON",
    "JUAN",
    "LAYS",
    "LILIAN",
    "LOUIS",
    "HONEY-INA",
    "MIKE",
    "THOUSAND-ENA",
    "NEWTON",
    "SAM",
    "RAFAEL ARAUJO",
    "NATAL",
    "GABRIEL",
    "DENISE",
    "ELISIANY",
    "MARLUS",
    "BRUNELY",
    "SHEILA",
    "TOTAL"
  ];
}

var nameMan = new NameManager();
